name: My test and linter chek

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          pip install poetry flake8
          make install
      - name: Run linter
        run: make lint
